### ISSUE TITLE
Unused ct variable in unittests

### ISSUE THREAD

**Issue by deviator** [burner/StringBuffer#1]
[Here](https://github.com/burner/StringBuffer/blob/master/source/stringbuffer.d#L128) and [here](https://github.com/burner/StringBuffer/blob/master/source/stringbuffer.d#L223) defined `Size` as ct parameter, but didn't used in function body. Maybe it must use in first line of `localTest` `alias SmallStringBuf = StringBufferImpl!Size`?

**Comment by burner** [comment]
thanks, should fine now
